dist: xenial
language: cpp
compiler:
  - gcc
addons:
  apt:
    update: true
    packages:
    - libmysqlclient-dev libsqlite3-dev
    - lcov
services:
  - mysql
script:
  - mysql -e 'CREATE DATABASE ormplusplus;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - sudo mysql_upgrade -uroot -proot
  - make all run BUILD=coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)